"""add_check_constraints

Revision ID: 0f7fd3ba3b68
Revises: 8c3af8c48d6c
Create Date: 2026-08-06 21:56:29.815361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f7fd3ba3b68'
down_revision: Union[str, Sequence[str], None] = '8c3af8c48d6c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint('ck_nacha_files_batch_count_pos', 'nacha_files', 'total_batch_count >= 1')
    op.create_check_constraint('ck_nacha_files_block_count_pos', 'nacha_files', 'total_block_count >= 1')
    op.create_check_constraint('ck_nacha_files_credit_nonneg', 'nacha_files', 'total_credit_amount >= 0')
    op.create_check_constraint('ck_nacha_files_entry_count_pos', 'nacha_files', 'total_entry_count >= 1')
    op.create_check_constraint('ck_payments_amount_positive', 'payments', 'amount > 0')
    op.create_check_constraint('ck_vendors_account_number_nonempty', 'vendors', 'length(account_number) >= 1')
    op.create_check_constraint('ck_vendors_routing_number_format', 'vendors', "routing_number ~ '^[0-9]{9}$'")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('ck_vendors_routing_number_format', 'vendors', type_='check')
    op.drop_constraint('ck_vendors_account_number_nonempty', 'vendors', type_='check')
    op.drop_constraint('ck_payments_amount_positive', 'payments', type_='check')
    op.drop_constraint('ck_nacha_files_entry_count_pos', 'nacha_files', type_='check')
    op.drop_constraint('ck_nacha_files_credit_nonneg', 'nacha_files', type_='check')
    op.drop_constraint('ck_nacha_files_block_count_pos', 'nacha_files', type_='check')
    op.drop_constraint('ck_nacha_files_batch_count_pos', 'nacha_files', type_='check')
    # ### end Alembic commands ###
