"""add_upload_batch_model

Revision ID: 7117f86f4b64
Revises: 0f7fd3ba3b68
Create Date: 2026-08-07 19:11:44.357912

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7117f86f4b64'
down_revision: Union[str, Sequence[str], None] = '0f7fd3ba3b68'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('upload_batches',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('batch_number', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('file_type', sa.String(length=50), nullable=False),
    sa.Column('total_rows', sa.Integer(), nullable=False),
    sa.Column('valid_rows_count', sa.Integer(), nullable=False),
    sa.Column('error_rows_count', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.Enum('PARSED', 'PARTIALLY_FAILED', 'FAILED', 'PROCESSED', name='batchstatus'), nullable=False),
    sa.Column('created_by_user_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_upload_batches_batch_number'), 'upload_batches', ['batch_number'], unique=False)
    op.add_column('payments', sa.Column('batch_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_payments_batch_id'), 'payments', ['batch_id'], unique=False)
    op.create_foreign_key(None, 'payments', 'upload_batches', ['batch_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_index(op.f('ix_payments_batch_id'), table_name='payments')
    op.drop_column('payments', 'batch_id')
    op.drop_index(op.f('ix_upload_batches_batch_number'), table_name='upload_batches')
    op.drop_table('upload_batches')
    # ### end Alembic commands ###
