"""add_payment_fingerprint_columns

Revision ID: 891382018f16
Revises: 7117f86f4b64
Create Date: 2026-08-07 19:26:59.221407

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '891382018f16'
down_revision: Union[str, Sequence[str], None] = '7117f86f4b64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('payments', sa.Column('fingerprint', sa.String(length=64), nullable=True))
    op.add_column('payments', sa.Column('is_duplicate_override', sa.Boolean(), server_default=sa.text('false'), nullable=False))
    op.create_index(op.f('ix_payments_fingerprint'), 'payments', ['fingerprint'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_payments_fingerprint'), table_name='payments')
    op.drop_column('payments', 'is_duplicate_override')
    op.drop_column('payments', 'fingerprint')
    # ### end Alembic commands ###
