"""add_vendor_remittances_table_and_vendor_email

Revision ID: 895301f9dffd
Revises: 49d1848b40f2
Create Date: 2026-08-07 19:43:05.748271

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '895301f9dffd'
down_revision: Union[str, Sequence[str], None] = '49d1848b40f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vendor_remittances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('vendor_id', sa.UUID(), nullable=False),
    sa.Column('nacha_file_id', sa.UUID(), nullable=True),
    sa.Column('payment_id', sa.UUID(), nullable=True),
    sa.Column('recipient_email', sa.String(length=255), nullable=False),
    sa.Column('vendor_name', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('effective_date', sa.Date(), nullable=False),
    sa.Column('invoice_reference', sa.String(length=80), nullable=True),
    sa.Column('subject', sa.String(length=255), nullable=False),
    sa.Column('body_text', sa.Text(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'SENT', 'FAILED', name='remittancestatus'), nullable=False),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.String(length=255), nullable=True),
    sa.Column('resend_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['nacha_file_id'], ['nacha_files.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['vendor_id'], ['vendors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vendor_remittances_nacha_file_id'), 'vendor_remittances', ['nacha_file_id'], unique=False)
    op.create_index(op.f('ix_vendor_remittances_payment_id'), 'vendor_remittances', ['payment_id'], unique=False)
    op.create_index(op.f('ix_vendor_remittances_status'), 'vendor_remittances', ['status'], unique=False)
    op.create_index(op.f('ix_vendor_remittances_vendor_id'), 'vendor_remittances', ['vendor_id'], unique=False)
    op.create_index(op.f('ix_vendor_remittances_vendor_name'), 'vendor_remittances', ['vendor_name'], unique=False)
    op.add_column('vendors', sa.Column('email', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('vendors', 'email')
    op.drop_index(op.f('ix_vendor_remittances_vendor_name'), table_name='vendor_remittances')
    op.drop_index(op.f('ix_vendor_remittances_vendor_id'), table_name='vendor_remittances')
    op.drop_index(op.f('ix_vendor_remittances_status'), table_name='vendor_remittances')
    op.drop_index(op.f('ix_vendor_remittances_payment_id'), table_name='vendor_remittances')
    op.drop_index(op.f('ix_vendor_remittances_nacha_file_id'), table_name='vendor_remittances')
    op.drop_table('vendor_remittances')
    # ### end Alembic commands ###
