"""widen_columns_for_encrypted_bank_details

Revision ID: d6bd0bf83b8d
Revises: 895301f9dffd
Create Date: 2026-08-07 19:55:09.132211

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6bd0bf83b8d'
down_revision: Union[str, Sequence[str], None] = '895301f9dffd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vendor_change_requests', 'requested_routing_number',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('vendor_change_requests', 'requested_account_number',
               existing_type=sa.VARCHAR(length=17),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('vendors', 'routing_number',
               existing_type=sa.VARCHAR(length=9),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.alter_column('vendors', 'account_number',
               existing_type=sa.VARCHAR(length=17),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.drop_constraint('ck_vendors_account_number_nonempty', 'vendors', type_='check')
    op.drop_constraint('ck_vendors_routing_number_format', 'vendors', type_='check')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('vendors', 'account_number',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=17),
               existing_nullable=False)
    op.alter_column('vendors', 'routing_number',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)
    op.alter_column('vendor_change_requests', 'requested_account_number',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=17),
               existing_nullable=False)
    op.alter_column('vendor_change_requests', 'requested_routing_number',
               existing_type=sa.String(length=255),
               type_=sa.VARCHAR(length=9),
               existing_nullable=False)
    # ### end Alembic commands ###
